# Copied from https://raw.githubusercontent.com/ekmett/lens/master/.travis.yml
language: haskell

env:
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.4
  - GHCVER=head
  # - >
  #   GHCVER=7.4.2
  #   MODE="-fsafe"

matrix:
  allow_failures:
    # NOTE (SM): this is only temporary, as it seems to be only Travis CI
    # where I have trouble building it with GHC 7.8.4. On my local machine it
    # works smoothly.
    - env: GHCVER=7.8.4
    - env: GHCVER=head

before_install:
  # If $GHCVER is the one travis has, don't bother reinstalling it.
  # We can also have faster builds by installing some libraries with
  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
  # with cabal-1.18.
  - |
    # Install the GHC we want from hvr's PPA
    travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    travis_retry sudo apt-get update
    travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy alex
    export CABAL=cabal-1.18
    export PATH=/opt/ghc/$GHCVER/bin:$PATH

  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
  - $CABAL update

install:
  - make install

