# Adapted from https://github.com/commercialhaskell/all-cabal-hashes-tool/blob/master/.travis.yml

# we use c for ocaml, stack automatically installs the correct GHC
language: c

# really means "use containerised environment and hence caching"

sudo: false
env:
  - OPAMYES=1

cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.local/bin/
  - $HOME/.stack
  - .stack-work/
  
addons:
  apt:
    sources:
      - avsm
    packages:
    - camlp4-extra
    - libgmp-dev
    - maude
    - ocaml
    - ocaml-native-compilers
    - opam

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack
  - stack --no-terminal setup

install:
  # pre-build 'mwc-random' and 'SHA' as otherwise Travis CI sometimes runs out of memory
  - stack build mwc-random SHA -j 1
  - stack install

  # SAPIC
  - opam init
  - eval `opam config env`
  - stack install
  - cd plugins/sapic && make

script:
  - tamarin-prover test
   # TODO(katriel) test SAPIC?

